# @package _global_
name: ${agent.name}_${model.name}_t${model.temperature}
save_path: temperature${model.temperature}_fp${model.frequency_penalty}_pp${presence_penalty}_${keyword}

is_call_api: False

model:
  temperature: 0
  max_tokens: 2048
  top_p: 1
  frequency_penalty: 0
  presence_penalty: 0

agent:
  name: 'azure_openapi_call'
  _target_: src.${agent.name}.Agent


