# @package _global_
name: ${agent.name}_${model.name}
save_path: temperature${model.temperature}_${keyword}

is_call_api: False

model:
  name: 'default'
  temperature: 0
  max_tokens: 2048
  top_p: 1
  frequency_penalty: 0
  presence_penalty: 0

agent:
  name: 'agent'
  _target_: src.${agent.name}.Agent

